/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.util.ArrayList;
import model.Operacao;

/**
 *
 * @author unifgaraujo
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    
    private String operacao;
    private double resultado,numero;
    
    
    public Janela() {
        initComponents();
        this.resultado=0f;
        this.numero=0f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Visor = new javax.swing.JTextField();
        for_ground = new javax.swing.JButton();
        for_ground1 = new javax.swing.JButton();
        for_ground2 = new javax.swing.JButton();
        for_ground3 = new javax.swing.JButton();
        for_ground4 = new javax.swing.JButton();
        for_ground5 = new javax.swing.JButton();
        for_ground6 = new javax.swing.JButton();
        for_ground7 = new javax.swing.JButton();
        for_ground8 = new javax.swing.JButton();
        for_ground9 = new javax.swing.JButton();
        for_ground10 = new javax.swing.JButton();
        for_ground11 = new javax.swing.JButton();
        for_ground12 = new javax.swing.JButton();
        for_ground13 = new javax.swing.JButton();
        for_ground14 = new javax.swing.JButton();
        for_ground15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        Visor.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        Visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisorActionPerformed(evt);
            }
        });

        for_ground.setBackground(new java.awt.Color(255, 255, 255));
        for_ground.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground.setForeground(new java.awt.Color(0, 0, 0));
        for_ground.setText("8");
        for_ground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_groundActionPerformed(evt);
            }
        });

        for_ground1.setBackground(new java.awt.Color(255, 255, 255));
        for_ground1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground1.setForeground(new java.awt.Color(0, 0, 0));
        for_ground1.setText("9");
        for_ground1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground1ActionPerformed(evt);
            }
        });

        for_ground2.setBackground(new java.awt.Color(255, 255, 255));
        for_ground2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground2.setForeground(new java.awt.Color(0, 0, 0));
        for_ground2.setText("/");
        for_ground2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground2ActionPerformed(evt);
            }
        });

        for_ground3.setBackground(new java.awt.Color(255, 255, 255));
        for_ground3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground3.setForeground(new java.awt.Color(0, 0, 0));
        for_ground3.setText("7");
        for_ground3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground3ActionPerformed(evt);
            }
        });

        for_ground4.setBackground(new java.awt.Color(255, 255, 255));
        for_ground4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground4.setForeground(new java.awt.Color(0, 0, 0));
        for_ground4.setText("4");
        for_ground4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground4ActionPerformed(evt);
            }
        });

        for_ground5.setBackground(new java.awt.Color(255, 255, 255));
        for_ground5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground5.setForeground(new java.awt.Color(0, 0, 0));
        for_ground5.setText("5");
        for_ground5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground5ActionPerformed(evt);
            }
        });

        for_ground6.setBackground(new java.awt.Color(255, 255, 255));
        for_ground6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground6.setForeground(new java.awt.Color(0, 0, 0));
        for_ground6.setText("6");
        for_ground6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground6ActionPerformed(evt);
            }
        });

        for_ground7.setBackground(new java.awt.Color(255, 255, 255));
        for_ground7.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground7.setForeground(new java.awt.Color(0, 0, 0));
        for_ground7.setText("X");
        for_ground7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground7ActionPerformed(evt);
            }
        });

        for_ground8.setBackground(new java.awt.Color(255, 255, 255));
        for_ground8.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground8.setForeground(new java.awt.Color(0, 0, 0));
        for_ground8.setText("1");
        for_ground8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground8ActionPerformed(evt);
            }
        });

        for_ground9.setBackground(new java.awt.Color(255, 255, 255));
        for_ground9.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground9.setForeground(new java.awt.Color(0, 0, 0));
        for_ground9.setText("2");
        for_ground9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground9ActionPerformed(evt);
            }
        });

        for_ground10.setBackground(new java.awt.Color(255, 255, 255));
        for_ground10.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground10.setForeground(new java.awt.Color(0, 0, 0));
        for_ground10.setText("3");
        for_ground10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground10ActionPerformed(evt);
            }
        });

        for_ground11.setBackground(new java.awt.Color(255, 255, 255));
        for_ground11.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground11.setForeground(new java.awt.Color(0, 0, 0));
        for_ground11.setText("-");
        for_ground11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground11ActionPerformed(evt);
            }
        });

        for_ground12.setBackground(new java.awt.Color(255, 255, 255));
        for_ground12.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground12.setForeground(new java.awt.Color(0, 0, 0));
        for_ground12.setText("c");
        for_ground12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground12ActionPerformed(evt);
            }
        });

        for_ground13.setBackground(new java.awt.Color(255, 255, 255));
        for_ground13.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground13.setForeground(new java.awt.Color(0, 0, 0));
        for_ground13.setText("0");
        for_ground13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground13ActionPerformed(evt);
            }
        });

        for_ground14.setBackground(new java.awt.Color(255, 255, 255));
        for_ground14.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground14.setForeground(new java.awt.Color(0, 0, 0));
        for_ground14.setText("=");
        for_ground14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground14ActionPerformed(evt);
            }
        });

        for_ground15.setBackground(new java.awt.Color(255, 255, 255));
        for_ground15.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        for_ground15.setForeground(new java.awt.Color(0, 0, 0));
        for_ground15.setText("+");
        for_ground15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_ground15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(216, 216, 216)
                                        .addComponent(for_ground11))
                                    .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(for_ground3)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(for_ground2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(for_ground12)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground13)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(for_ground15)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(for_ground8)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground9)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(for_ground4)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground5)
                                .addGap(18, 18, 18)
                                .addComponent(for_ground6)
                                .addGap(4, 4, 4)
                                .addComponent(for_ground7)))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_ground, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_ground5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_ground9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_ground13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_ground12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisorActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_VisorActionPerformed

    private void for_ground8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground8ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="1";
        Visor.setText(texto);
        
    }//GEN-LAST:event_for_ground8ActionPerformed

    private void for_ground3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground3ActionPerformed
        // TODO add your handling code here:
         String texto=Visor.getText();
        texto+="7";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground3ActionPerformed

    private void for_groundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_groundActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="8";
        Visor.setText(texto);
    }//GEN-LAST:event_for_groundActionPerformed

    private void for_ground1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground1ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="9";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground1ActionPerformed

    private void for_ground4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground4ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="4";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground4ActionPerformed

    private void for_ground5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground5ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="5";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground5ActionPerformed

    private void for_ground6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground6ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="6";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground6ActionPerformed

    private void for_ground9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground9ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="2";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground9ActionPerformed

    private void for_ground10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground10ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="3";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground10ActionPerformed

    private void for_ground13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground13ActionPerformed
        // TODO add your handling code here:
           String texto=Visor.getText();
        texto+="0";
        Visor.setText(texto);
    }//GEN-LAST:event_for_ground13ActionPerformed

    private void for_ground12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground12ActionPerformed
        // TODO add your handling code here:
        Visor.setText("");
    }//GEN-LAST:event_for_ground12ActionPerformed

    private void for_ground15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground15ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Operacao>soma=new ArrayList<>();
        
      this.numero=Double.parseDouble(Visor.getText());
      this. for_ground12ActionPerformed(evt);
      this.operacao="soma";
              

    }//GEN-LAST:event_for_ground15ActionPerformed

    private void for_ground14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground14ActionPerformed
        // TODO add your handling code here:
              double numeroLocal=Double.parseDouble(Visor.getText());
               model.Operacao op=new Operacao(this.numero,numeroLocal,this.operacao);
      
          Visor.setText(String.valueOf(op.calcula()));
      
    }//GEN-LAST:event_for_ground14ActionPerformed

    private void for_ground7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground7ActionPerformed
        // TODO add your handling code here:
         this.numero=Double.parseDouble(Visor.getText());
      this. for_ground12ActionPerformed(evt);
      this.operacao="multiplicacao";
    }//GEN-LAST:event_for_ground7ActionPerformed

    private void for_ground11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground11ActionPerformed
        // TODO add your handling code here:
         this.numero=Double.parseDouble(Visor.getText());
      this. for_ground12ActionPerformed(evt);
      this.operacao="subtracao";
    }//GEN-LAST:event_for_ground11ActionPerformed

    private void for_ground2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_ground2ActionPerformed
        // TODO add your handling code here:
         this.numero=Double.parseDouble(Visor.getText());
      this. for_ground12ActionPerformed(evt);
      this.operacao="divisao";
    }//GEN-LAST:event_for_ground2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Visor;
    private javax.swing.JButton for_ground;
    private javax.swing.JButton for_ground1;
    private javax.swing.JButton for_ground10;
    private javax.swing.JButton for_ground11;
    private javax.swing.JButton for_ground12;
    private javax.swing.JButton for_ground13;
    private javax.swing.JButton for_ground14;
    private javax.swing.JButton for_ground15;
    private javax.swing.JButton for_ground2;
    private javax.swing.JButton for_ground3;
    private javax.swing.JButton for_ground4;
    private javax.swing.JButton for_ground5;
    private javax.swing.JButton for_ground6;
    private javax.swing.JButton for_ground7;
    private javax.swing.JButton for_ground8;
    private javax.swing.JButton for_ground9;
    // End of variables declaration//GEN-END:variables
}
