/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerCadastro;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifgaraujo
 */
public class Cadastro_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Frame
     */
    public Cadastro_Frame() {
        initComponents();
        c=new ControllerCadastro(this);
    }

    public JButton getBT_CADASTRAR() {
        return BT_CADASTRAR;
    }

    public void setBT_CADASTRAR(JButton BT_CADASTRAR) {
        this.BT_CADASTRAR = BT_CADASTRAR;
    }

    public JLabel getLBL_NOME_CADASTRO() {
        return LBL_NOME_CADASTRO;
    }

    public void setLBL_NOME_CADASTRO(JLabel LBL_NOME_CADASTRO) {
        this.LBL_NOME_CADASTRO = LBL_NOME_CADASTRO;
    }

    public JLabel getLBL_SENHA_CADASTRO() {
        return LBL_SENHA_CADASTRO;
    }

    public void setLBL_SENHA_CADASTRO(JLabel LBL_SENHA_CADASTRO) {
        this.LBL_SENHA_CADASTRO = LBL_SENHA_CADASTRO;
    }

    public JLabel getLBL_USUARIO_CADASTRO() {
        return LBL_USUARIO_CADASTRO;
    }

    public void setLBL_USUARIO_CADASTRO(JLabel LBL_USUARIO_CADASTRO) {
        this.LBL_USUARIO_CADASTRO = LBL_USUARIO_CADASTRO;
    }

    public JTextField getTXT_NOME_CADASTRO() {
        return TXT_NOME_CADASTRO;
    }

    public void setTXT_NOME_CADASTRO(JTextField TXT_NOME_CADASTRO) {
        this.TXT_NOME_CADASTRO = TXT_NOME_CADASTRO;
    }

    public JTextField getTXT_SENHA_CADASTRO() {
        return TXT_SENHA_CADASTRO;
    }

    public void setTXT_SENHA_CADASTRO(JTextField TXT_SENHA_CADASTRO) {
        this.TXT_SENHA_CADASTRO = TXT_SENHA_CADASTRO;
    }

    public JTextField getTXT_USUARIO_CADASTRO() {
        return TXT_USUARIO_CADASTRO;
    }

    public void setTXT_USUARIO_CADASTRO(JTextField TXT_USUARIO_CADASTRO) {
        this.TXT_USUARIO_CADASTRO = TXT_USUARIO_CADASTRO;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL_NOME_CADASTRO = new javax.swing.JLabel();
        TXT_NOME_CADASTRO = new javax.swing.JTextField();
        TXT_USUARIO_CADASTRO = new javax.swing.JTextField();
        LBL_USUARIO_CADASTRO = new javax.swing.JLabel();
        TXT_SENHA_CADASTRO = new javax.swing.JTextField();
        LBL_SENHA_CADASTRO = new javax.swing.JLabel();
        BT_CADASTRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema_Alunos");

        LBL_NOME_CADASTRO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LBL_NOME_CADASTRO.setText("Nome:");

        TXT_NOME_CADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NOME_CADASTROActionPerformed(evt);
            }
        });

        TXT_USUARIO_CADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_USUARIO_CADASTROActionPerformed(evt);
            }
        });

        LBL_USUARIO_CADASTRO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LBL_USUARIO_CADASTRO.setText("Usuario");

        TXT_SENHA_CADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_SENHA_CADASTROActionPerformed(evt);
            }
        });

        LBL_SENHA_CADASTRO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LBL_SENHA_CADASTRO.setText("Senha");

        BT_CADASTRAR.setText("Cadastrar");
        BT_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CADASTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_SENHA_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(TXT_SENHA_CADASTRO, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_USUARIO_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(TXT_USUARIO_CADASTRO))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LBL_NOME_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(TXT_NOME_CADASTRO)))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_NOME_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_NOME_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_USUARIO_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_USUARIO_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_SENHA_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_SENHA_CADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(BT_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_NOME_CADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NOME_CADASTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NOME_CADASTROActionPerformed

    private void TXT_USUARIO_CADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_USUARIO_CADASTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_USUARIO_CADASTROActionPerformed

    private void TXT_SENHA_CADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_SENHA_CADASTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_SENHA_CADASTROActionPerformed

    private void BT_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CADASTRARActionPerformed
       c.salvarAluno();
    }//GEN-LAST:event_BT_CADASTRARActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Cadastro_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Cadastro_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Cadastro_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Cadastro_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cadastro_Frame().setVisible(true);
//            }
//        });
//    }
private ControllerCadastro c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CADASTRAR;
    private javax.swing.JLabel LBL_NOME_CADASTRO;
    private javax.swing.JLabel LBL_SENHA_CADASTRO;
    private javax.swing.JLabel LBL_USUARIO_CADASTRO;
    private javax.swing.JTextField TXT_NOME_CADASTRO;
    private javax.swing.JTextField TXT_SENHA_CADASTRO;
    private javax.swing.JTextField TXT_USUARIO_CADASTRO;
    // End of variables declaration//GEN-END:variables
}
