/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Controle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author unifgaraujo
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        c=new Controle(this);
    }

    public JButton getBt_dividir1() {
        return bt_dividir1;
    }

    public void setBt_dividir1(JButton bt_dividir1) {
        this.bt_dividir1 = bt_dividir1;
    }

    public JButton getBt_limpar() {
        return bt_limpar;
    }

    public void setBt_limpar(JButton bt_limpar) {
        this.bt_limpar = bt_limpar;
    }

    public JButton getBt_mult() {
        return bt_mult;
    }

    public void setBt_mult(JButton bt_mult) {
        this.bt_mult = bt_mult;
    }

    public JButton getBt_somar1() {
        return bt_somar1;
    }

    public void setBt_somar1(JButton bt_somar1) {
        this.bt_somar1 = bt_somar1;
    }

    public JButton getBt_sub() {
        return bt_sub;
    }

    public void setBt_sub(JButton bt_sub) {
        this.bt_sub = bt_sub;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLbl_num1() {
        return lbl_num1;
    }

    public void setLbl_num1(JLabel lbl_num1) {
        this.lbl_num1 = lbl_num1;
    }

    public JLabel getLbl_num2() {
        return lbl_num2;
    }

    public void setLbl_num2(JLabel lbl_num2) {
        this.lbl_num2 = lbl_num2;
    }

    public JLabel getLbl_resultado() {
        return lbl_resultado;
    }

    public void setLbl_resultado(JLabel lbl_resultado) {
        this.lbl_resultado = lbl_resultado;
    }

    public JTextField getTxt_num1() {
        return txt_num1;
    }

    public void setTxt_num1(JTextField txt_num1) {
        this.txt_num1 = txt_num1;
    }

    public JTextField getTxt_num2() {
        return txt_num2;
    }

    public void setTxt_num2(JTextField txt_num2) {
        this.txt_num2 = txt_num2;
    }

    public JTextField getTxt_resultado() {
        return txt_resultado;
    }

    public void setTxt_resultado(JTextField txt_resultado) {
        this.txt_resultado = txt_resultado;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_num1 = new javax.swing.JLabel();
        txt_num1 = new javax.swing.JTextField();
        lbl_num2 = new javax.swing.JLabel();
        txt_num2 = new javax.swing.JTextField();
        bt_sub = new javax.swing.JButton();
        bt_somar1 = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();
        txt_resultado = new javax.swing.JTextField();
        bt_mult = new javax.swing.JButton();
        bt_limpar = new javax.swing.JButton();
        bt_dividir1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("soma numerosV2");

        lbl_num1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_num1.setText("Numero 1:");

        lbl_num2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_num2.setText("Numero 2:");

        bt_sub.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_sub.setText("Subtrair");
        bt_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_subActionPerformed(evt);
            }
        });

        bt_somar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_somar1.setText("Somar");
        bt_somar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_somar1ActionPerformed(evt);
            }
        });

        lbl_resultado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_resultado.setText("Resultado:");

        bt_mult.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_mult.setText("Multiplicar");
        bt_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_multActionPerformed(evt);
            }
        });

        bt_limpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        bt_dividir1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bt_dividir1.setText("Dividir");
        bt_dividir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dividir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_resultado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_num2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_somar1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(bt_sub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_dividir1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_mult)))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_somar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_dividir1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_mult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        // TODO add your handling code here:
c.controlarLimpar();
    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_somar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_somar1ActionPerformed
        // TODO add your handling code here:

//        double n1 = Double.parseDouble(txt_num1.getText());
//        double n2 = Double.parseDouble(txt_num2.getText());
//        double r = n1 + n2;
//        txt_resultado.setText(String.valueOf(r));
c.controleSomar();
    }//GEN-LAST:event_bt_somar1ActionPerformed

    private void bt_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_subActionPerformed
        // TODO add your handling code here:

        double n1 = Double.parseDouble(txt_num1.getText());
        double n2 = Double.parseDouble(txt_num2.getText());
        double r = n1 - n2;
        txt_resultado.setText(String.valueOf(r));
    }//GEN-LAST:event_bt_subActionPerformed

    private void bt_dividir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dividir1ActionPerformed
        // TODO add your handling code here:

        double n1 = Double.parseDouble(txt_num1.getText());
        double n2 = Double.parseDouble(txt_num2.getText());
        double r = n1 / n2;
        txt_resultado.setText(String.valueOf(r));
    }//GEN-LAST:event_bt_dividir1ActionPerformed

    private void bt_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_multActionPerformed
        // TODO add your handling code here:

        double n1 = Double.parseDouble(txt_num1.getText());
        double n2 = Double.parseDouble(txt_num2.getText());
        double r = n1 * n2;
        txt_resultado.setText(String.valueOf(r));
    }//GEN-LAST:event_bt_multActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Janela().setVisible(true);
//            }
//        });
//    }

    private Controle c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_dividir1;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_mult;
    private javax.swing.JButton bt_somar1;
    private javax.swing.JButton bt_sub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_num1;
    private javax.swing.JLabel lbl_num2;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_num1;
    private javax.swing.JTextField txt_num2;
    private javax.swing.JTextField txt_resultado;
    // End of variables declaration//GEN-END:variables
}
