/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author unifgaraujo
 */
public class Loggin_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Loggin_Frame
     */
    public Loggin_Frame() {
        initComponents();
    }

    public JButton getBT_CADASTRO() {
        return BT_CADASTRO;
    }

    public void setBT_CADASTRO(JButton BT_CADASTRO) {
        this.BT_CADASTRO = BT_CADASTRO;
    }

    public JButton getBT_LOGIN() {
        return BT_LOGIN;
    }

    public void setBT_LOGIN(JButton BT_LOGIN) {
        this.BT_LOGIN = BT_LOGIN;
    }

    public JLabel getLBL_SENHA_LOGIN() {
        return LBL_SENHA_LOGIN;
    }

    public void setLBL_SENHA_LOGIN(JLabel LBL_SENHA_LOGIN) {
        this.LBL_SENHA_LOGIN = LBL_SENHA_LOGIN;
    }

    public JLabel getLBL_UUR_LOGIN() {
        return LBL_UUR_LOGIN;
    }

    public void setLBL_UUR_LOGIN(JLabel LBL_UUR_LOGIN) {
        this.LBL_UUR_LOGIN = LBL_UUR_LOGIN;
    }

    public JTextField getTXT_SENHA_LOGIN() {
        return TXT_SENHA_LOGIN;
    }

    public void setTXT_SENHA_LOGIN(JTextField TXT_SENHA_LOGIN) {
        this.TXT_SENHA_LOGIN = TXT_SENHA_LOGIN;
    }

    public JTextField getTXT_USER_LOGIN() {
        return TXT_USER_LOGIN;
    }

    public void setTXT_USER_LOGIN(JTextField TXT_USER_LOGIN) {
        this.TXT_USER_LOGIN = TXT_USER_LOGIN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL_UUR_LOGIN = new javax.swing.JLabel();
        TXT_USER_LOGIN = new javax.swing.JTextField();
        LBL_SENHA_LOGIN = new javax.swing.JLabel();
        TXT_SENHA_LOGIN = new javax.swing.JTextField();
        BT_LOGIN = new javax.swing.JButton();
        BT_CADASTRO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema_Alunos");

        LBL_UUR_LOGIN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LBL_UUR_LOGIN.setText("Usuario:");

        LBL_SENHA_LOGIN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LBL_SENHA_LOGIN.setText("Senha");

        BT_LOGIN.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BT_LOGIN.setText("Login");
        BT_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_LOGINActionPerformed(evt);
            }
        });

        BT_CADASTRO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BT_CADASTRO.setText("Cadastro");
        BT_CADASTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CADASTROActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(BT_CADASTRO))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LBL_SENHA_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(TXT_SENHA_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LBL_UUR_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(TXT_USER_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(BT_LOGIN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_UUR_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_USER_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_SENHA_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_SENHA_LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BT_LOGIN)
                .addGap(33, 33, 33)
                .addComponent(BT_CADASTRO)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_CADASTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CADASTROActionPerformed
        // TODO add your handling code here:
        Cadastro_Frame cd=new Cadastro_Frame();
        cd.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_BT_CADASTROActionPerformed

    private void BT_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_LOGINActionPerformed
        // TODO add your handling code here:
//        ALT_ESQ_FRAME sef=new   ALT_ESQ_FRAME();
//        sef.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_BT_LOGINActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Loggin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Loggin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Loggin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Loggin_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Loggin_Frame().setVisible(true);
//            }
//        });
//    }
private ControllerLogin c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_CADASTRO;
    private javax.swing.JButton BT_LOGIN;
    private javax.swing.JLabel LBL_SENHA_LOGIN;
    private javax.swing.JLabel LBL_UUR_LOGIN;
    private javax.swing.JTextField TXT_SENHA_LOGIN;
    private javax.swing.JTextField TXT_USER_LOGIN;
    // End of variables declaration//GEN-END:variables
}
